name: goodvas_demo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  injectable: 2.3.1
  get_it: 7.6.4

  flutter_bloc: ^8.1.3

  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: 2.4.6
  flutter_gen_runner: 5.3.2
  injectable_generator: 2.4.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images